name: Run tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v1

    # CACHE
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

    - name: Install libs
      run: yarn
    
    - name: Run tests
      run: yarn test:ci

    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        name: PR test
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage/clover.xml
