name: Update kubernetes stack

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Publish to registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: mariasiuvlad/pt-web
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest

      - name: Deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_BASE64 }}
        with:
          args: rollout restart deployment pt-web
            rollout restart deployment pt-storybook
